//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbassyAPI.Models.DataModels
{
    using EmbassyAPI.Models.ViewModels;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class embassyEntities : DbContext
    {
        public embassyEntities()
            : base("name=embassyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NEWS> NEWS { get; set; }
        public DbSet<NEWS_LOGO> NEWS_LOGO { get; set; }
        public DbSet<NEWSAUTHOR> NEWSAUTHORS { get; set; }        
    }
}
