//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbassyAPI.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public decimal NEWSID { get; set; }
        public string NEWSTITLE { get; set; }
        public string NEWSCONTENT { get; set; }
        public Nullable<System.DateTime> DATEPOSTED { get; set; }
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        public string ISDELETED { get; set; }
        public Nullable<decimal> AUTHORID { get; set; }
        public string ISARCHIVE { get; set; }
    
        public virtual NEWSAUTHOR NEWSAUTHOR { get; set; }
    }
}
